import type { AgentManifestV1 } from "@/utils/manifest/types";

// Fantasy adjectives for migration names (like Drizzle)
const ADJECTIVES = [
  "ancient",
  "bold",
  "brave",
  "bright",
  "calm",
  "cool",
  "cosmic",
  "crimson",
  "curious",
  "daring",
  "divine",
  "eager",
  "elegant",
  "fierce",
  "gentle",
  "golden",
  "gracious",
  "happy",
  "honest",
  "humble",
  "jolly",
  "joyful",
  "kind",
  "lively",
  "lucky",
  "magic",
  "mighty",
  "modern",
  "noble",
  "peaceful",
  "polished",
  "proud",
  "quick",
  "quiet",
  "radiant",
  "rapid",
  "royal",
  "serene",
  "shiny",
  "silent",
  "sleek",
  "swift",
  "tender",
  "timely",
  "trusting",
  "vivid",
  "warm",
  "wild",
  "wise",
  "witty",
  "zesty",
] as const;

// Fantasy nouns for migration names
const NOUNS = [
  "arrow",
  "aurora",
  "breeze",
  "canyon",
  "comet",
  "crystal",
  "dawn",
  "diamond",
  "dragon",
  "dream",
  "eagle",
  "echo",
  "falcon",
  "flame",
  "forest",
  "galaxy",
  "garden",
  "harbor",
  "harmony",
  "horizon",
  "island",
  "journey",
  "lagoon",
  "meadow",
  "miracle",
  "moon",
  "mountain",
  "nebula",
  "ocean",
  "orchard",
  "phoenix",
  "pioneer",
  "prairie",
  "quasar",
  "rainbow",
  "rapids",
  "river",
  "shadow",
  "silence",
  "sky",
  "solar",
  "star",
  "storm",
  "summit",
  "sunrise",
  "sunset",
  "thunder",
  "tide",
  "valley",
  "voyage",
  "waterfall",
  "wave",
  "wildflower",
  "wisdom",
  "zenith",
] as const;

function getRandomElement<T extends readonly string[]>(arr: T): T[number] {
  return arr[Math.floor(Math.random() * arr.length)] as T[number];
}

export function createVersionId(version: number): string {
  const adjective = getRandomElement(ADJECTIVES);
  const noun = getRandomElement(NOUNS);
  const versionStr = version.toString().padStart(4, "0");
  return `${versionStr}_${adjective}_${noun}`;
}

export function getManifestHash(manifest: AgentManifestV1): string {
  return manifest.codeHash;
}
