import { access, readFile, rm, mkdtemp } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { buildAgent } from "@kalphq/compiler";

import type { AgentManifestV3 } from "@/utils/manifest/types";
export type { AgentManifestV3 } from "@/utils/manifest/types";
export { computePushHash } from "@/utils/ir/hashIR";

/**
 * Reads and compiles an agent into a pushable manifest.
 */
export async function readAgentManifest(params: {
  cwd: string;
  agentName: string;
}): Promise<AgentManifestV3> {
  const { cwd, agentName } = params;
  const agentPath = join(cwd, "agents", agentName, "index.ts");
  await access(agentPath);

  // Use a temporary directory for the compiler output
  const tempOutDir = await mkdtemp(join(tmpdir(), "kalp-build-"));

  try {
    // Build the agent - compiler produces ir.bundles with all handler code
    await buildAgent(agentPath, tempOutDir, cwd);

    // Load the IR generated by the compiler (includes bundles with code)
    const irContent = await readFile(join(tempOutDir, "ir.json"), "utf-8");
    const ir = JSON.parse(irContent);

    return {
      format: "kalp-agent-manifest",
      schemaVersion: 3,
      ir,
      metadata: {
        generatedAt: new Date().toISOString(),
      },
    };
  } finally {
    // Cleanup temp build directory
    await rm(tempOutDir, { recursive: true, force: true });
  }
}
