// packages/cli/src/utils/manifest/index.ts
import { access, readFile, readdir, rm, mkdtemp } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { buildAgent } from "@kalphq/compiler";
import { loadAgentModule, cleanupTempDir } from "@/utils/manifest/build";
import type { AgentManifestV2 } from "@/utils/manifest/types";

export type {
  AgentManifestV2,
  LoadedAgentModule,
} from "@/utils/manifest/types";
export type { HandlerMap, HandlerEntry } from "@/utils/manifest/handlers";
export { computePushHash } from "@/utils/ir/hashIR";

/**
 * Reads and compiles an agent into a pushable manifest.
 */
export async function readAgentManifest(params: {
  cwd: string;
  agentName: string;
}): Promise<AgentManifestV2> {
  const { cwd, agentName } = params;
  const agentPath = join(cwd, "agents", agentName, "index.ts");
  await access(agentPath);

  // Use a temporary directory for the compiler output
  const tempOutDir = await mkdtemp(join(tmpdir(), "kalp-build-"));

  try {
    // 1. Build the agent using the official compiler pipeline
    await buildAgent(agentPath, tempOutDir, cwd);

    // 2. Load the IR generated by the compiler
    const irContent = await readFile(join(tempOutDir, "ir.json"), "utf-8");
    const ir = JSON.parse(irContent);

    // 3. Collect bundled handlers
    const handlersDir = join(tempOutDir, "handlers");
    const handlerFiles = await readdir(handlersDir);
    const handlers: any = {};

    for (const file of handlerFiles) {
      if (!file.endsWith(".js")) continue;
      const code = await readFile(join(handlersDir, file), "utf-8");

      // Filename format: name.hash.js
      const parts = file.split(".");
      const hash = parts[1] || "no-hash";

      handlers[file] = {
        name: file,
        code,
        hash,
        size: Buffer.byteLength(code),
      };
    }

    // 4. Also load the module to get the codeHash (for legacy reasons)
    const loaded = await loadAgentModule(agentPath, cwd);
    const codeHash = loaded.codeHash;
    await cleanupTempDir(loaded.tempDir);

    return {
      format: "kalp-agent-manifest",
      schemaVersion: 2,
      codeHash,
      ir,
      handlers,
      metadata: {
        generatedAt: new Date().toISOString(),
      },
    };
  } finally {
    // Cleanup temp build directory
    await rm(tempOutDir, { recursive: true, force: true });
  }
}
