import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import ts from "typescript";
import { loadProjectConfig } from "@/utils/project-config";

const GENERATED_HEADER = `// 🦋 Kalp Generated Types
// This file is auto-generated. Do not edit manually.
`;

const GENERATED_MCP_HEADER = `// 🦋 Kalp Generated MCP Types
// This file is auto-generated by \`kalp mcp generate\`.
// Do not edit manually.
`;

type AIProvider = "openai" | "anthropic" | "openrouter" | "custom";

interface GeneratedTypeConfig {
  secrets: string[];
  provider: AIProvider;
  customModels: string[];
}

const DEFAULT_PROVIDER: AIProvider = "openai";

function sanitizeSecrets(input: unknown): string[] {
  if (!Array.isArray(input)) return [];
  return input
    .filter((value): value is string => typeof value === "string")
    .map((value) => value.trim())
    .filter(Boolean)
    .sort((a, b) => a.localeCompare(b));
}

function sanitizeCustomModels(input: unknown): string[] {
  if (!Array.isArray(input)) return [];
  return input
    .filter((value): value is string => typeof value === "string")
    .map((value) => value.trim())
    .filter(Boolean)
    .sort((a, b) => a.localeCompare(b));
}

function sanitizeProvider(input: unknown): AIProvider {
  if (
    input === "openai" ||
    input === "anthropic" ||
    input === "openrouter" ||
    input === "custom"
  ) {
    return input;
  }
  return DEFAULT_PROVIDER;
}

function parseSecretsFromConfigText(configContent: string): string[] {
  const secretsMatch = configContent.match(/secrets:\s*\[([^\]]*)\]/);
  if (!secretsMatch) return [];
  const secretsArray = secretsMatch[1] ?? "";
  const secretMatches = secretsArray.match(/"([^"]+)"/g);
  if (!secretMatches) return [];
  return secretMatches
    .map((match) => match.replace(/"/g, "").trim())
    .filter(Boolean)
    .sort((a, b) => a.localeCompare(b));
}

function parseProviderFromConfigText(configContent: string): AIProvider {
  const providerMatch = configContent.match(
    /provider:\s*"(openai|anthropic|openrouter|custom)"/,
  );
  return sanitizeProvider(providerMatch?.[1]);
}

function parseCustomModelsFromConfigText(configContent: string): string[] {
  const modelsMatch = configContent.match(/customModels:\s*\[([^\]]*)\]/);
  if (!modelsMatch) return [];
  const modelsArray = modelsMatch[1] ?? "";
  const modelMatches = modelsArray.match(/"([^"]+)"/g);
  if (!modelMatches) return [];
  return modelMatches
    .map((match) => match.replace(/"/g, "").trim())
    .filter(Boolean)
    .sort((a, b) => a.localeCompare(b));
}

async function readConfigForTypes(cwd: string): Promise<GeneratedTypeConfig> {
  try {
    const { raw } = await loadProjectConfig(cwd);
    const aiConfig =
      raw.ai && typeof raw.ai === "object" ? (raw.ai as Record<string, unknown>) : {};

    return {
      secrets: sanitizeSecrets(raw.secrets),
      provider: sanitizeProvider(aiConfig.provider),
      customModels: sanitizeCustomModels(aiConfig.customModels),
    };
  } catch {
    const configPath = join(cwd, "kalp.config.ts");
    const configContent = await readFile(configPath, "utf-8").catch(() => "");
    return {
      secrets: parseSecretsFromConfigText(configContent),
      provider: parseProviderFromConfigText(configContent),
      customModels: parseCustomModelsFromConfigText(configContent),
    };
  }
}

function toStringTuple(values: string[]): string {
  if (values.length === 0) return "readonly []";
  return `readonly [${values.map((value) => JSON.stringify(value)).join(", ")}]`;
}

function buildKalpDtsContent(): string {
  return `import "@kalphq/sdk";
import "./.kalp/mcp.types";
import type {
  RegisteredSecretKeys,
  ConfiguredAIProvider,
  ConfiguredAICustomModels,
} from "./.kalp/types";

declare module "@kalphq/sdk" {
  interface SecretsRegistry {
    keys: RegisteredSecretKeys;
  }

  interface KalpAIEnvironment {
    provider: ConfiguredAIProvider;
    customModels: ConfiguredAICustomModels;
  }
}
`;
}

function buildEmptyMcpTypesContent(): string {
  return `${GENERATED_MCP_HEADER}import "@kalphq/sdk";

declare module "@kalphq/sdk" {
  interface McpRegistry {}
}
`;
}

export async function writeMcpTypes(cwd: string, content: string): Promise<string> {
  const kalpDir = join(cwd, ".kalp");
  const mcpTypesPath = join(kalpDir, "mcp.types.d.ts");
  await mkdir(kalpDir, { recursive: true });
  await writeFile(mcpTypesPath, content, "utf-8");
  await updateKalpDts(cwd);
  await updateTsconfig(cwd);
  return mcpTypesPath;
}

async function ensureMcpTypesFile(cwd: string): Promise<void> {
  const kalpDir = join(cwd, ".kalp");
  const mcpTypesPath = join(kalpDir, "mcp.types.d.ts");

  try {
    await access(mcpTypesPath);
    return;
  } catch {
    await writeMcpTypes(cwd, buildEmptyMcpTypesContent());
  }
}

/**
 * Generate .kalp/types.d.ts and ensure local module augmentations are wired.
 */
export async function generateTypes(cwd: string): Promise<void> {
  const kalpDir = join(cwd, ".kalp");
  const typesPath = join(kalpDir, "types.d.ts");
  const config = await readConfigForTypes(cwd);

  await mkdir(kalpDir, { recursive: true });

  const typesContent = `${GENERATED_HEADER}/**
 * Registered secrets from kalp.config.ts
 * @generated
 */
export type RegisteredSecretKeys = ${toStringTuple(config.secrets)};

/**
 * AI provider resolved from kalp.config.ts
 * @generated
 */
export type ConfiguredAIProvider = ${JSON.stringify(config.provider)};

/**
 * Custom model suggestions resolved from kalp.config.ts
 * @generated
 */
export type ConfiguredAICustomModels = ${toStringTuple(config.customModels)};
`;

  await writeFile(typesPath, typesContent, "utf-8");
  await ensureMcpTypesFile(cwd);
  await updateKalpDts(cwd);
  await updateTsconfig(cwd);
}

/**
 * Ensure kalp.d.ts exists and contains SDK module augmentations.
 */
export async function updateKalpDts(cwd: string): Promise<void> {
  const kalpDtsPath = join(cwd, "kalp.d.ts");
  const content = buildKalpDtsContent();

  try {
    await access(kalpDtsPath);
    const current = await readFile(kalpDtsPath, "utf-8");
    if (current.trim() === content.trim()) {
      return;
    }
  } catch {
    // file does not exist yet
  }

  await writeFile(kalpDtsPath, content, "utf-8");
}

/**
 * Ensure tsconfig includes kalp.d.ts and generated .kalp types.
 */
export async function updateTsconfig(cwd: string): Promise<void> {
  const tsconfigPath = join(cwd, "tsconfig.json");

  try {
    const content = await readFile(tsconfigPath, "utf-8");
    const parsed = ts.parseConfigFileTextToJson(tsconfigPath, content);
    if (parsed.error || !parsed.config || typeof parsed.config !== "object") {
      return;
    }

    const config = parsed.config as {
      include?: string[];
    };

    if (!Array.isArray(config.include)) {
      config.include = [];
    }

    const required = ["kalp.d.ts", ".kalp/types.d.ts", ".kalp/mcp.types.d.ts"];
    for (const includePath of required) {
      if (!config.include.includes(includePath)) {
        config.include.push(includePath);
      }
    }

    await writeFile(tsconfigPath, JSON.stringify(config, null, 2), "utf-8");
  } catch {
    // no-op
  }
}
