/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudioRouteImport } from './routes/_studio'
import { Route as StudioIndexRouteImport } from './routes/_studio.index'
import { Route as ReplayExecutionIdRouteImport } from './routes/replay.$executionId'
import { Route as StudioStorageRouteImport } from './routes/_studio.storage'
import { Route as StudioSettingsRouteImport } from './routes/_studio.settings'
import { Route as StudioSecretsRouteImport } from './routes/_studio.secrets'
import { Route as StudioMembersRouteImport } from './routes/_studio.members'
import { Route as StudioAccountRouteImport } from './routes/_studio.account'
import { Route as StudioSettingsIndexRouteImport } from './routes/_studio.settings.index'
import { Route as StudioSettingsSecretsRouteImport } from './routes/_studio.settings.secrets'
import { Route as StudioSettingsMcpRouteImport } from './routes/_studio.settings.mcp'
import { Route as StudioSettingsAiRouteImport } from './routes/_studio.settings.ai'
import { Route as StudioAgentAgentNameRouteImport } from './routes/_studio.agent.$agentName'
import { Route as StudioAgentAgentNameIndexRouteImport } from './routes/_studio.agent.$agentName.index'
import { Route as StudioAgentAgentNameTopologyRouteImport } from './routes/_studio.agent.$agentName.topology'
import { Route as StudioAgentAgentNameStateRouteImport } from './routes/_studio.agent.$agentName.state'
import { Route as StudioAgentAgentNameReplayRouteImport } from './routes/_studio.agent.$agentName.replay'
import { Route as StudioAgentAgentNameChatRouteImport } from './routes/_studio.agent.$agentName.chat'
import { Route as StudioAgentAgentNameActivityRouteImport } from './routes/_studio.agent.$agentName.activity'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const ReplayExecutionIdRoute = ReplayExecutionIdRouteImport.update({
  id: '/replay/$executionId',
  path: '/replay/$executionId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioStorageRoute = StudioStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSettingsRoute = StudioSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSecretsRoute = StudioSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => StudioRoute,
} as any)
const StudioMembersRoute = StudioMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAccountRoute = StudioAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSettingsIndexRoute = StudioSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioSettingsRoute,
} as any)
const StudioSettingsSecretsRoute = StudioSettingsSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => StudioSettingsRoute,
} as any)
const StudioSettingsMcpRoute = StudioSettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => StudioSettingsRoute,
} as any)
const StudioSettingsAiRoute = StudioSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => StudioSettingsRoute,
} as any)
const StudioAgentAgentNameRoute = StudioAgentAgentNameRouteImport.update({
  id: '/agent/$agentName',
  path: '/agent/$agentName',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAgentAgentNameIndexRoute =
  StudioAgentAgentNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudioAgentAgentNameRoute,
  } as any)
const StudioAgentAgentNameTopologyRoute =
  StudioAgentAgentNameTopologyRouteImport.update({
    id: '/topology',
    path: '/topology',
    getParentRoute: () => StudioAgentAgentNameRoute,
  } as any)
const StudioAgentAgentNameStateRoute =
  StudioAgentAgentNameStateRouteImport.update({
    id: '/state',
    path: '/state',
    getParentRoute: () => StudioAgentAgentNameRoute,
  } as any)
const StudioAgentAgentNameReplayRoute =
  StudioAgentAgentNameReplayRouteImport.update({
    id: '/replay',
    path: '/replay',
    getParentRoute: () => StudioAgentAgentNameRoute,
  } as any)
const StudioAgentAgentNameChatRoute =
  StudioAgentAgentNameChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => StudioAgentAgentNameRoute,
  } as any)
const StudioAgentAgentNameActivityRoute =
  StudioAgentAgentNameActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => StudioAgentAgentNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof StudioIndexRoute
  '/login': typeof LoginRoute
  '/account': typeof StudioAccountRoute
  '/members': typeof StudioMembersRoute
  '/secrets': typeof StudioSecretsRoute
  '/settings': typeof StudioSettingsRouteWithChildren
  '/storage': typeof StudioStorageRoute
  '/replay/$executionId': typeof ReplayExecutionIdRoute
  '/agent/$agentName': typeof StudioAgentAgentNameRouteWithChildren
  '/settings/ai': typeof StudioSettingsAiRoute
  '/settings/mcp': typeof StudioSettingsMcpRoute
  '/settings/secrets': typeof StudioSettingsSecretsRoute
  '/settings/': typeof StudioSettingsIndexRoute
  '/agent/$agentName/activity': typeof StudioAgentAgentNameActivityRoute
  '/agent/$agentName/chat': typeof StudioAgentAgentNameChatRoute
  '/agent/$agentName/replay': typeof StudioAgentAgentNameReplayRoute
  '/agent/$agentName/state': typeof StudioAgentAgentNameStateRoute
  '/agent/$agentName/topology': typeof StudioAgentAgentNameTopologyRoute
  '/agent/$agentName/': typeof StudioAgentAgentNameIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/account': typeof StudioAccountRoute
  '/members': typeof StudioMembersRoute
  '/secrets': typeof StudioSecretsRoute
  '/storage': typeof StudioStorageRoute
  '/replay/$executionId': typeof ReplayExecutionIdRoute
  '/': typeof StudioIndexRoute
  '/settings/ai': typeof StudioSettingsAiRoute
  '/settings/mcp': typeof StudioSettingsMcpRoute
  '/settings/secrets': typeof StudioSettingsSecretsRoute
  '/settings': typeof StudioSettingsIndexRoute
  '/agent/$agentName/activity': typeof StudioAgentAgentNameActivityRoute
  '/agent/$agentName/chat': typeof StudioAgentAgentNameChatRoute
  '/agent/$agentName/replay': typeof StudioAgentAgentNameReplayRoute
  '/agent/$agentName/state': typeof StudioAgentAgentNameStateRoute
  '/agent/$agentName/topology': typeof StudioAgentAgentNameTopologyRoute
  '/agent/$agentName': typeof StudioAgentAgentNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_studio': typeof StudioRouteWithChildren
  '/login': typeof LoginRoute
  '/_studio/account': typeof StudioAccountRoute
  '/_studio/members': typeof StudioMembersRoute
  '/_studio/secrets': typeof StudioSecretsRoute
  '/_studio/settings': typeof StudioSettingsRouteWithChildren
  '/_studio/storage': typeof StudioStorageRoute
  '/replay/$executionId': typeof ReplayExecutionIdRoute
  '/_studio/': typeof StudioIndexRoute
  '/_studio/agent/$agentName': typeof StudioAgentAgentNameRouteWithChildren
  '/_studio/settings/ai': typeof StudioSettingsAiRoute
  '/_studio/settings/mcp': typeof StudioSettingsMcpRoute
  '/_studio/settings/secrets': typeof StudioSettingsSecretsRoute
  '/_studio/settings/': typeof StudioSettingsIndexRoute
  '/_studio/agent/$agentName/activity': typeof StudioAgentAgentNameActivityRoute
  '/_studio/agent/$agentName/chat': typeof StudioAgentAgentNameChatRoute
  '/_studio/agent/$agentName/replay': typeof StudioAgentAgentNameReplayRoute
  '/_studio/agent/$agentName/state': typeof StudioAgentAgentNameStateRoute
  '/_studio/agent/$agentName/topology': typeof StudioAgentAgentNameTopologyRoute
  '/_studio/agent/$agentName/': typeof StudioAgentAgentNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/members'
    | '/secrets'
    | '/settings'
    | '/storage'
    | '/replay/$executionId'
    | '/agent/$agentName'
    | '/settings/ai'
    | '/settings/mcp'
    | '/settings/secrets'
    | '/settings/'
    | '/agent/$agentName/activity'
    | '/agent/$agentName/chat'
    | '/agent/$agentName/replay'
    | '/agent/$agentName/state'
    | '/agent/$agentName/topology'
    | '/agent/$agentName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/account'
    | '/members'
    | '/secrets'
    | '/storage'
    | '/replay/$executionId'
    | '/'
    | '/settings/ai'
    | '/settings/mcp'
    | '/settings/secrets'
    | '/settings'
    | '/agent/$agentName/activity'
    | '/agent/$agentName/chat'
    | '/agent/$agentName/replay'
    | '/agent/$agentName/state'
    | '/agent/$agentName/topology'
    | '/agent/$agentName'
  id:
    | '__root__'
    | '/_studio'
    | '/login'
    | '/_studio/account'
    | '/_studio/members'
    | '/_studio/secrets'
    | '/_studio/settings'
    | '/_studio/storage'
    | '/replay/$executionId'
    | '/_studio/'
    | '/_studio/agent/$agentName'
    | '/_studio/settings/ai'
    | '/_studio/settings/mcp'
    | '/_studio/settings/secrets'
    | '/_studio/settings/'
    | '/_studio/agent/$agentName/activity'
    | '/_studio/agent/$agentName/chat'
    | '/_studio/agent/$agentName/replay'
    | '/_studio/agent/$agentName/state'
    | '/_studio/agent/$agentName/topology'
    | '/_studio/agent/$agentName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StudioRoute: typeof StudioRouteWithChildren
  LoginRoute: typeof LoginRoute
  ReplayExecutionIdRoute: typeof ReplayExecutionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio': {
      id: '/_studio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/': {
      id: '/_studio/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/replay/$executionId': {
      id: '/replay/$executionId'
      path: '/replay/$executionId'
      fullPath: '/replay/$executionId'
      preLoaderRoute: typeof ReplayExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/storage': {
      id: '/_studio/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StudioStorageRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/settings': {
      id: '/_studio/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof StudioSettingsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/secrets': {
      id: '/_studio/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof StudioSecretsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/members': {
      id: '/_studio/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof StudioMembersRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/account': {
      id: '/_studio/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof StudioAccountRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/settings/': {
      id: '/_studio/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof StudioSettingsIndexRouteImport
      parentRoute: typeof StudioSettingsRoute
    }
    '/_studio/settings/secrets': {
      id: '/_studio/settings/secrets'
      path: '/secrets'
      fullPath: '/settings/secrets'
      preLoaderRoute: typeof StudioSettingsSecretsRouteImport
      parentRoute: typeof StudioSettingsRoute
    }
    '/_studio/settings/mcp': {
      id: '/_studio/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof StudioSettingsMcpRouteImport
      parentRoute: typeof StudioSettingsRoute
    }
    '/_studio/settings/ai': {
      id: '/_studio/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof StudioSettingsAiRouteImport
      parentRoute: typeof StudioSettingsRoute
    }
    '/_studio/agent/$agentName': {
      id: '/_studio/agent/$agentName'
      path: '/agent/$agentName'
      fullPath: '/agent/$agentName'
      preLoaderRoute: typeof StudioAgentAgentNameRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/agent/$agentName/': {
      id: '/_studio/agent/$agentName/'
      path: '/'
      fullPath: '/agent/$agentName/'
      preLoaderRoute: typeof StudioAgentAgentNameIndexRouteImport
      parentRoute: typeof StudioAgentAgentNameRoute
    }
    '/_studio/agent/$agentName/topology': {
      id: '/_studio/agent/$agentName/topology'
      path: '/topology'
      fullPath: '/agent/$agentName/topology'
      preLoaderRoute: typeof StudioAgentAgentNameTopologyRouteImport
      parentRoute: typeof StudioAgentAgentNameRoute
    }
    '/_studio/agent/$agentName/state': {
      id: '/_studio/agent/$agentName/state'
      path: '/state'
      fullPath: '/agent/$agentName/state'
      preLoaderRoute: typeof StudioAgentAgentNameStateRouteImport
      parentRoute: typeof StudioAgentAgentNameRoute
    }
    '/_studio/agent/$agentName/replay': {
      id: '/_studio/agent/$agentName/replay'
      path: '/replay'
      fullPath: '/agent/$agentName/replay'
      preLoaderRoute: typeof StudioAgentAgentNameReplayRouteImport
      parentRoute: typeof StudioAgentAgentNameRoute
    }
    '/_studio/agent/$agentName/chat': {
      id: '/_studio/agent/$agentName/chat'
      path: '/chat'
      fullPath: '/agent/$agentName/chat'
      preLoaderRoute: typeof StudioAgentAgentNameChatRouteImport
      parentRoute: typeof StudioAgentAgentNameRoute
    }
    '/_studio/agent/$agentName/activity': {
      id: '/_studio/agent/$agentName/activity'
      path: '/activity'
      fullPath: '/agent/$agentName/activity'
      preLoaderRoute: typeof StudioAgentAgentNameActivityRouteImport
      parentRoute: typeof StudioAgentAgentNameRoute
    }
  }
}

interface StudioSettingsRouteChildren {
  StudioSettingsAiRoute: typeof StudioSettingsAiRoute
  StudioSettingsMcpRoute: typeof StudioSettingsMcpRoute
  StudioSettingsSecretsRoute: typeof StudioSettingsSecretsRoute
  StudioSettingsIndexRoute: typeof StudioSettingsIndexRoute
}

const StudioSettingsRouteChildren: StudioSettingsRouteChildren = {
  StudioSettingsAiRoute: StudioSettingsAiRoute,
  StudioSettingsMcpRoute: StudioSettingsMcpRoute,
  StudioSettingsSecretsRoute: StudioSettingsSecretsRoute,
  StudioSettingsIndexRoute: StudioSettingsIndexRoute,
}

const StudioSettingsRouteWithChildren = StudioSettingsRoute._addFileChildren(
  StudioSettingsRouteChildren,
)

interface StudioAgentAgentNameRouteChildren {
  StudioAgentAgentNameActivityRoute: typeof StudioAgentAgentNameActivityRoute
  StudioAgentAgentNameChatRoute: typeof StudioAgentAgentNameChatRoute
  StudioAgentAgentNameReplayRoute: typeof StudioAgentAgentNameReplayRoute
  StudioAgentAgentNameStateRoute: typeof StudioAgentAgentNameStateRoute
  StudioAgentAgentNameTopologyRoute: typeof StudioAgentAgentNameTopologyRoute
  StudioAgentAgentNameIndexRoute: typeof StudioAgentAgentNameIndexRoute
}

const StudioAgentAgentNameRouteChildren: StudioAgentAgentNameRouteChildren = {
  StudioAgentAgentNameActivityRoute: StudioAgentAgentNameActivityRoute,
  StudioAgentAgentNameChatRoute: StudioAgentAgentNameChatRoute,
  StudioAgentAgentNameReplayRoute: StudioAgentAgentNameReplayRoute,
  StudioAgentAgentNameStateRoute: StudioAgentAgentNameStateRoute,
  StudioAgentAgentNameTopologyRoute: StudioAgentAgentNameTopologyRoute,
  StudioAgentAgentNameIndexRoute: StudioAgentAgentNameIndexRoute,
}

const StudioAgentAgentNameRouteWithChildren =
  StudioAgentAgentNameRoute._addFileChildren(StudioAgentAgentNameRouteChildren)

interface StudioRouteChildren {
  StudioAccountRoute: typeof StudioAccountRoute
  StudioMembersRoute: typeof StudioMembersRoute
  StudioSecretsRoute: typeof StudioSecretsRoute
  StudioSettingsRoute: typeof StudioSettingsRouteWithChildren
  StudioStorageRoute: typeof StudioStorageRoute
  StudioIndexRoute: typeof StudioIndexRoute
  StudioAgentAgentNameRoute: typeof StudioAgentAgentNameRouteWithChildren
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioAccountRoute: StudioAccountRoute,
  StudioMembersRoute: StudioMembersRoute,
  StudioSecretsRoute: StudioSecretsRoute,
  StudioSettingsRoute: StudioSettingsRouteWithChildren,
  StudioStorageRoute: StudioStorageRoute,
  StudioIndexRoute: StudioIndexRoute,
  StudioAgentAgentNameRoute: StudioAgentAgentNameRouteWithChildren,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StudioRoute: StudioRouteWithChildren,
  LoginRoute: LoginRoute,
  ReplayExecutionIdRoute: ReplayExecutionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
