/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudioRouteImport } from './routes/_studio'
import { Route as StudioIndexRouteImport } from './routes/_studio.index'
import { Route as ReplayExecutionIdRouteImport } from './routes/replay.$executionId'
import { Route as StudioAgentAgentNameRouteImport } from './routes/_studio.agent.$agentName'

const StudioRoute = StudioRouteImport.update({
  id: '/_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const ReplayExecutionIdRoute = ReplayExecutionIdRouteImport.update({
  id: '/replay/$executionId',
  path: '/replay/$executionId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioAgentAgentNameRoute = StudioAgentAgentNameRouteImport.update({
  id: '/agent/$agentName',
  path: '/agent/$agentName',
  getParentRoute: () => StudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StudioIndexRoute
  '/login': typeof LoginRoute
  '/agent/$agentName': typeof StudioAgentAgentNameRoute
  '/replay/$executionId': typeof ReplayExecutionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof StudioIndexRoute
  '/login': typeof LoginRoute
  '/agent/$agentName': typeof StudioAgentAgentNameRoute
  '/replay/$executionId': typeof ReplayExecutionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_studio': typeof StudioRoute
  '/': typeof StudioIndexRoute
  '/login': typeof LoginRoute
  '/agent/$agentName': typeof StudioAgentAgentNameRoute
  '/replay/$executionId': typeof ReplayExecutionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/agent/$agentName' | '/replay/$executionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/agent/$agentName' | '/replay/$executionId'
  id: '__root__' | '/' | '/login' | '/agent/$agentName' | '/replay/$executionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StudioRoute: typeof StudioRoute
  LoginRoute: typeof LoginRoute
  ReplayExecutionIdRoute: typeof ReplayExecutionIdRoute
}
export interface StudioRouteChildren {
  StudioIndexRoute: typeof StudioIndexRoute
  StudioAgentAgentNameRoute: typeof StudioAgentAgentNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRouteImport
    }
    '/replay/$executionId': {
      id: '/replay/$executionId'
      path: '/replay/$executionId'
      fullPath: '/replay/$executionId'
      preLoaderRoute: typeof ReplayExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$agentName': {
      id: '/agent/$agentName'
      path: '/agent/$agentName'
      fullPath: '/agent/$agentName'
      preLoaderRoute: typeof StudioAgentAgentNameRouteImport
      parentRoute: typeof StudioRouteImport
    }
  }
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioIndexRoute: StudioIndexRoute,
  StudioAgentAgentNameRoute: StudioAgentAgentNameRoute,
}
const StudioRouteWithChildren = StudioRoute._addFileChildren(StudioRouteChildren)
const rootRouteChildren: RootRouteChildren = {
  StudioRoute: StudioRouteWithChildren,
  LoginRoute: LoginRoute,
  ReplayExecutionIdRoute: ReplayExecutionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
